---
- name: Deploy Apache on CentOS VM
  hosts: httpd_hosts_stg
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: present

    - name: Start and Enable Apache
      service: 
        name: httpd
        state: started
        enabled: yes